//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtalVideo.Localizations.AdminPanel {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminPanel() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DgtalVideo.Localizations.AdminPanel.AdminPanel", typeof(AdminPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Actions.
        /// </summary>
        public static string Admin_panel_actions {
            get {
                return ResourceManager.GetString("Admin_panel_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a work.
        /// </summary>
        public static string Admin_panel_Add_a_work {
            get {
                return ResourceManager.GetString("Admin_panel_Add_a_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Admin_panel_btn_cancel {
            get {
                return ResourceManager.GetString("Admin_panel_btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Admin_panel_btn_delete {
            get {
                return ResourceManager.GetString("Admin_panel_btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string Admin_panel_category {
            get {
                return ResourceManager.GetString("Admin_panel_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment text.
        /// </summary>
        public static string Admin_panel_comment_text {
            get {
                return ResourceManager.GetString("Admin_panel_comment_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer inquiries.
        /// </summary>
        public static string Admin_panel_customer_inquiries {
            get {
                return ResourceManager.GetString("Admin_panel_customer_inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string Admin_panel_date {
            get {
                return ResourceManager.GetString("Admin_panel_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete this review?.
        /// </summary>
        public static string Admin_panel_delete_this_review {
            get {
                return ResourceManager.GetString("Admin_panel_delete_this_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete this work?.
        /// </summary>
        public static string Admin_panel_delete_this_work {
            get {
                return ResourceManager.GetString("Admin_panel_delete_this_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string Admin_panel_description {
            get {
                return ResourceManager.GetString("Admin_panel_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Admin_panel_edit {
            get {
                return ResourceManager.GetString("Admin_panel_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing the work.
        /// </summary>
        public static string Admin_panel_editing_the_work {
            get {
                return ResourceManager.GetString("Admin_panel_editing_the_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin panel.
        /// </summary>
        public static string Admin_panel_header {
            get {
                return ResourceManager.GetString("Admin_panel_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Headline.
        /// </summary>
        public static string Admin_panel_Headline {
            get {
                return ResourceManager.GetString("Admin_panel_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leave a review.
        /// </summary>
        public static string Admin_panel_leave_a_review {
            get {
                return ResourceManager.GetString("Admin_panel_leave_a_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link to video.
        /// </summary>
        public static string Admin_panel_link_to_video {
            get {
                return ResourceManager.GetString("Admin_panel_link_to_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Admin_panel_name {
            get {
                return ResourceManager.GetString("Admin_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string Admin_panel_new {
            get {
                return ResourceManager.GetString("Admin_panel_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no new requests yet..
        /// </summary>
        public static string Admin_panel_no_new_request {
            get {
                return ResourceManager.GetString("Admin_panel_no_new_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string Admin_panel_open {
            get {
                return ResourceManager.GetString("Admin_panel_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number.
        /// </summary>
        public static string Admin_panel_phone_number {
            get {
                return ResourceManager.GetString("Admin_panel_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Portfolio.
        /// </summary>
        public static string Admin_panel_portfolio {
            get {
                return ResourceManager.GetString("Admin_panel_portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read.
        /// </summary>
        public static string Admin_panel_read {
            get {
                return ResourceManager.GetString("Admin_panel_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reviews.
        /// </summary>
        public static string Admin_panel_reviews {
            get {
                return ResourceManager.GetString("Admin_panel_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save review.
        /// </summary>
        public static string Admin_panel_save_review {
            get {
                return ResourceManager.GetString("Admin_panel_save_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save work.
        /// </summary>
        public static string Admin_panel_save_work {
            get {
                return ResourceManager.GetString("Admin_panel_save_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brief description.
        /// </summary>
        public static string Admin_panel_short_description {
            get {
                return ResourceManager.GetString("Admin_panel_short_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        public static string Admin_panel_status {
            get {
                return ResourceManager.GetString("Admin_panel_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string Admin_panel_text {
            get {
                return ResourceManager.GetString("Admin_panel_text", resourceCulture);
            }
        }
    }
}
