//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtalVideo.Localizations.CostCalculator {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CostCalculator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CostCalculator() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DgtalVideo.Localizations.CostCalculator.CostCalculator", typeof(CostCalculator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate.
        /// </summary>
        public static string Cost_calculator_calculate {
            get {
                return ResourceManager.GetString("Cost_calculator_calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is color correction necessary?.
        /// </summary>
        public static string Cost_calculator_color_correction {
            get {
                return ResourceManager.GetString("Cost_calculator_color_correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tight deadline? Need a quick installation?.
        /// </summary>
        public static string Cost_calculator_deadline {
            get {
                return ResourceManager.GetString("Cost_calculator_deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estimated total cost:.
        /// </summary>
        public static string Cost_calculator_estimated_total_cost {
            get {
                return ResourceManager.GetString("Cost_calculator_estimated_total_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Which format are you interested in?.
        /// </summary>
        public static string Cost_calculator_format {
            get {
                return ResourceManager.GetString("Cost_calculator_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cost Calculator.
        /// </summary>
        public static string Cost_calculator_header {
            get {
                return ResourceManager.GetString("Cost_calculator_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is it necessary to add subtitles?.
        /// </summary>
        public static string Cost_calculator_necessary {
            get {
                return ResourceManager.GetString("Cost_calculator_necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is the volume of the source files?.
        /// </summary>
        public static string Cost_calculator_volume_of_the_sourse {
            get {
                return ResourceManager.GetString("Cost_calculator_volume_of_the_sourse", resourceCulture);
            }
        }
    }
}
