//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtalVideo.Localizations.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUs() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DgtalVideo.Localizations.Home.AboutUs", typeof(AboutUs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our Story.
        /// </summary>
        public static string About_us_our_story {
            get {
                return ResourceManager.GetString("About_us_our_story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A team of professionals passionate about their craft and striving for perfection in every shot..
        /// </summary>
        public static string About_us_team {
            get {
                return ResourceManager.GetString("About_us_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DgtalVideo started as a small editing studio for local brands. Today, we work with clients across Russia and beyond, creating video content for advertising, business, and personal projects..
        /// </summary>
        public static string About_us_text_part1 {
            get {
                return ResourceManager.GetString("About_us_text_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our philosophy is simple: high-quality editing is not just splicing shots together, but telling a story that evokes emotion and motivates action..
        /// </summary>
        public static string About_us_text_part2 {
            get {
                return ResourceManager.GetString("About_us_text_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We constantly keep up with video production trends, master new tools, and hone our craft to ensure that every project surpasses the last..
        /// </summary>
        public static string About_us_text_part3 {
            get {
                return ResourceManager.GetString("About_us_text_part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Millions of viewers have seen our projects on TV, on social media, in person at events, on advertising screens, in video courses, and on other platforms..
        /// </summary>
        public static string About_us_text_part4 {
            get {
                return ResourceManager.GetString("About_us_text_part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We work with professional video editing software—Adobe Premiere Pro, Adobe After Effects, DaVinci Resolve, and Sony Vegas—along with additional tools for audio and color processing..
        /// </summary>
        public static string About_us_text_part5 {
            get {
                return ResourceManager.GetString("About_us_text_part5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What programs do you use in your work?.
        /// </summary>
        public static string Header_about_us_text_part5 {
            get {
                return ResourceManager.GetString("Header_about_us_text_part5", resourceCulture);
            }
        }
    }
}
