//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtalVideo.Localizations.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexPage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DgtalVideo.Localizations.Home.IndexPage", typeof(IndexPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up to 3 rounds of revisions are included..
        /// </summary>
        public static string Index_3_rounds {
            get {
                return ResourceManager.GetString("Index_3_rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About Us.
        /// </summary>
        public static string Index_about_us {
            get {
                return ResourceManager.GetString("Index_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preserve your best travel moments with vivid videos that transport you back to the holiday atmosphere!.
        /// </summary>
        public static string Index_about_vacation_video {
            get {
                return ResourceManager.GetString("Index_about_vacation_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stand out from the competition with creative contest videos that grab attention.
        /// </summary>
        public static string Index_about_video_for_contests {
            get {
                return ResourceManager.GetString("Index_about_video_for_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Give the gift of emotion with unique video greetings for your loved ones for any occasion.
        /// </summary>
        public static string Index_about_video_greetings {
            get {
                return ResourceManager.GetString("Index_about_video_greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit a request.
        /// </summary>
        public static string Index_btn_submit_a_request {
            get {
                return ResourceManager.GetString("Index_btn_submit_a_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What makes up the budget?.
        /// </summary>
        public static string Index_budget {
            get {
                return ResourceManager.GetString("Index_budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate the cost.
        /// </summary>
        public static string Index_calculate_the_cost {
            get {
                return ResourceManager.GetString("Index_calculate_the_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commercials.
        /// </summary>
        public static string Index_commercials {
            get {
                return ResourceManager.GetString("Index_commercials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit a request, and we will contact you to discuss the project details..
        /// </summary>
        public static string Index_contact_discuss {
            get {
                return ResourceManager.GetString("Index_contact_discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corporate videos.
        /// </summary>
        public static string Index_corporate_videos {
            get {
                return ResourceManager.GetString("Index_corporate_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We create dynamic videos that capture attention and tell your story from the very first frame..
        /// </summary>
        public static string Index_create_video {
            get {
                return ResourceManager.GetString("Index_create_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer Reviews.
        /// </summary>
        public static string Index_customer_reviews {
            get {
                return ResourceManager.GetString("Index_customer_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail.
        /// </summary>
        public static string Index_email {
            get {
                return ResourceManager.GetString("Index_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frequently Asked Questions.
        /// </summary>
        public static string Index_FAQ {
            get {
                return ResourceManager.GetString("Index_FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timelines depend on the project&apos;s complexity and the studio&apos;s current workload. Typically, simple projects can be completed within 3–5 business days, while more complex ones may take 1–2 weeks. We always aim to agree on timelines with the client in advance..
        /// </summary>
        public static string Index_faq_about_how_long_video_editing {
            get {
                return ResourceManager.GetString("Index_faq_about_how_long_video_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We can deliver the finished video via cloud services (such as Google Drive or Dropbox) or send it by email, depending on the file size..
        /// </summary>
        public static string Index_faq_about_how_will_finished_be_delivered {
            get {
                return ResourceManager.GetString("Index_faq_about_how_will_finished_be_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, we offer the option to make revisions after the initial viewing. Typically, the service package includes a certain number of revisions, but we are always open to discussing additional changes and their cost..
        /// </summary>
        public static string Index_faq_about_make_changes {
            get {
                return ResourceManager.GetString("Index_faq_about_make_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes, we can help select music and sound design for your video. We have access to licensed music libraries and can offer several options to choose from, depending on the mood of your project..
        /// </summary>
        public static string Index_faq_about_provide_music {
            get {
                return ResourceManager.GetString("Index_faq_about_provide_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is the turnaround time for a video editing order?.
        /// </summary>
        public static string Index_faq_how_long_video_editing {
            get {
                return ResourceManager.GetString("Index_faq_how_long_video_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How will the finished video be delivered?.
        /// </summary>
        public static string Index_faq_how_will_finished_be_delivered {
            get {
                return ResourceManager.GetString("Index_faq_how_will_finished_be_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can I make changes to the video after the first draft?.
        /// </summary>
        public static string Index_faq_make_changes {
            get {
                return ResourceManager.GetString("Index_faq_make_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you provide music selection and sound design services?.
        /// </summary>
        public static string Index_faq_provide_music {
            get {
                return ResourceManager.GetString("Index_faq_provide_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please describe in detail the type of video you need; if you have a project brief, please attach it..
        /// </summary>
        public static string Index_faq1 {
            get {
                return ResourceManager.GetString("Index_faq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The cost of editing depends on the volume of material, the complexity of the work, and additional services (such as color grading or animation). We can offer fixed rates or a custom quote after discussing the project details..
        /// </summary>
        public static string Index_FAQ2 {
            get {
                return ResourceManager.GetString("Index_FAQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fixed estimate before work begins.
        /// </summary>
        public static string Index_fixed_estimate {
            get {
                return ResourceManager.GetString("Index_fixed_estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start small, find out the cost..
        /// </summary>
        public static string Index_footer_start_small {
            get {
                return ResourceManager.GetString("Index_footer_start_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We create video that works for your brand..
        /// </summary>
        public static string Index_for_your_brand {
            get {
                return ResourceManager.GetString("Index_for_your_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Free consultation.
        /// </summary>
        public static string Index_free_consultation {
            get {
                return ResourceManager.GetString("Index_free_consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Installation workflow.
        /// </summary>
        public static string Index_installation_workflow {
            get {
                return ResourceManager.GetString("Index_installation_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More about us.
        /// </summary>
        public static string Index_more_about_us {
            get {
                return ResourceManager.GetString("Index_more_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Music videos.
        /// </summary>
        public static string Index_music_videos {
            get {
                return ResourceManager.GetString("Index_music_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Index_name {
            get {
                return ResourceManager.GetString("Index_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How do I order installation, and what does the process involve?.
        /// </summary>
        public static string Index_order_installation {
            get {
                return ResourceManager.GetString("Index_order_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We specialize in editing various formats—from commercials to social media content..
        /// </summary>
        public static string Index_our_specialization {
            get {
                return ResourceManager.GetString("Index_our_specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill out the form on the right, and we will prepare a personalized proposal within 24 hours..
        /// </summary>
        public static string Index_personalized_proposal {
            get {
                return ResourceManager.GetString("Index_personalized_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number.
        /// </summary>
        public static string Index_phone_number {
            get {
                return ResourceManager.GetString("Index_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tell us about your project: video type, duration, timelines....
        /// </summary>
        public static string Index_placeholder_your_project {
            get {
                return ResourceManager.GetString("Index_placeholder_your_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Project Description.
        /// </summary>
        public static string Index_project_description {
            get {
                return ResourceManager.GetString("Index_project_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready-made video project.
        /// </summary>
        public static string Index_ready_made {
            get {
                return ResourceManager.GetString("Index_ready_made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reels and Stories.
        /// </summary>
        public static string Index_reels_and_stories {
            get {
                return ResourceManager.GetString("Index_reels_and_stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What those who have already entrusted us with their projects say about us..
        /// </summary>
        public static string Index_reviews_part1 {
            get {
                return ResourceManager.GetString("Index_reviews_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See more works.
        /// </summary>
        public static string Index_see_more_works {
            get {
                return ResourceManager.GetString("Index_see_more_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DgtalVideo is a team of editors with experience in advertising, film, and digital media..
        /// </summary>
        public static string Index_text_block_part1 {
            get {
                return ResourceManager.GetString("Index_text_block_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на We use professional software and modern editing techniques to ensure your video stands out from the competition and achieves its goals..
        /// </summary>
        public static string Index_text_block_part2 {
            get {
                return ResourceManager.GetString("Index_text_block_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vacation video.
        /// </summary>
        public static string Index_vacation_video {
            get {
                return ResourceManager.GetString("Index_vacation_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video categories.
        /// </summary>
        public static string Index_video_categories {
            get {
                return ResourceManager.GetString("Index_video_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create eye-catching videos that grab attention and make your brand unforgettable.
        /// </summary>
        public static string Index_video_description_part1 {
            get {
                return ResourceManager.GetString("Index_video_description_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highlight your company&apos;s values ​​with professional corporate videos that inspire!.
        /// </summary>
        public static string Index_video_description_part2 {
            get {
                return ResourceManager.GetString("Index_video_description_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capture the magic of your day with touching wedding films that you will cherish for a lifetime.
        /// </summary>
        public static string Index_video_description_part3 {
            get {
                return ResourceManager.GetString("Index_video_description_part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Engage your audience with creative YouTube content that tells your story.
        /// </summary>
        public static string Index_video_description_part4 {
            get {
                return ResourceManager.GetString("Index_video_description_part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bring your music project to life with vibrant music videos that will stick in viewers&apos; minds.
        /// </summary>
        public static string Index_video_description_part5 {
            get {
                return ResourceManager.GetString("Index_video_description_part5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create short, dynamic videos that instantly grab attention on social media.
        /// </summary>
        public static string Index_video_description_part6 {
            get {
                return ResourceManager.GetString("Index_video_description_part6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Professional video editing.
        /// </summary>
        public static string Index_video_editing {
            get {
                return ResourceManager.GetString("Index_video_editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Videos for contests.
        /// </summary>
        public static string Index_video_for_contests {
            get {
                return ResourceManager.GetString("Index_video_for_contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video greetings.
        /// </summary>
        public static string Index_video_greetings {
            get {
                return ResourceManager.GetString("Index_video_greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wedding films.
        /// </summary>
        public static string Index_wedding_films {
            get {
                return ResourceManager.GetString("Index_wedding_films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your name.
        /// </summary>
        public static string Index_your_name {
            get {
                return ResourceManager.GetString("Index_your_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на YouTube content.
        /// </summary>
        public static string Index_youtube_content {
            get {
                return ResourceManager.GetString("Index_youtube_content", resourceCulture);
            }
        }
    }
}
