//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DgtalVideo.Localizations.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicePage() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DgtalVideo.Localizations.Home.ServicePage", typeof(ServicePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color correction.
        /// </summary>
        public static string Service_color_correction {
            get {
                return ResourceManager.GetString("Service_color_correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Animated titles, logos, infographics, and visual effects. We add dynamism and a professional look to your video..
        /// </summary>
        public static string Service_description_part3 {
            get {
                return ResourceManager.GetString("Service_description_part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact us for a free consultation and a cost estimate..
        /// </summary>
        public static string Services_contact_free_consultation {
            get {
                return ResourceManager.GetString("Services_contact_free_consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Editing from source material: cutting, splicing, pacing, and transitions. We work with any format—from raw footage to finished timelines..
        /// </summary>
        public static string Services_description_part1 {
            get {
                return ResourceManager.GetString("Services_description_part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio track cleanup; addition of music, sound effects, and voiceover; mixing and mastering of the final audio..
        /// </summary>
        public static string Services_description_part2 {
            get {
                return ResourceManager.GetString("Services_description_part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subtitling, translation, and content adaptation for various audiences and platforms..
        /// </summary>
        public static string Services_description_part4 {
            get {
                return ResourceManager.GetString("Services_description_part4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A full range of video editing services — from simple cutting to complex post-production..
        /// </summary>
        public static string Services_full_range {
            get {
                return ResourceManager.GetString("Services_full_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motion graphics.
        /// </summary>
        public static string Services_motion_graphics {
            get {
                return ResourceManager.GetString("Services_motion_graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Platform adaptation.
        /// </summary>
        public static string Services_platform_adaptation {
            get {
                return ResourceManager.GetString("Services_platform_adaptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preparing videos in the required formats and resolutions for YouTube, Instagram, TikTok, Telegram, and other platforms..
        /// </summary>
        public static string Services_preparing_video {
            get {
                return ResourceManager.GetString("Services_preparing_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Professional color correction and grading for a unified visual style. Adjustment of exposure, white balance, and color tones..
        /// </summary>
        public static string Services_proffesional_color {
            get {
                return ResourceManager.GetString("Services_proffesional_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready to start the project?.
        /// </summary>
        public static string Services_ready_start_project {
            get {
                return ResourceManager.GetString("Services_ready_start_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Services.
        /// </summary>
        public static string Services_services {
            get {
                return ResourceManager.GetString("Services_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound design.
        /// </summary>
        public static string Services_sound_design {
            get {
                return ResourceManager.GetString("Services_sound_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Submit a request.
        /// </summary>
        public static string Services_submit {
            get {
                return ResourceManager.GetString("Services_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subtitles and localization.
        /// </summary>
        public static string Services_subtitles {
            get {
                return ResourceManager.GetString("Services_subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Video editing.
        /// </summary>
        public static string Services_video_editing {
            get {
                return ResourceManager.GetString("Services_video_editing", resourceCulture);
            }
        }
    }
}
